### ISSUE TITLE
how does this work

### ISSUE THREAD

**Issue by cools9** [Kazooki123/LunarDB#4]
Unknown command. Type 'HELP' for available commands.
> HELP
Unknown command. Type 'HELP' for available commands.
> HELP
Unknown command. Type 'HELP' for available commands.
> 

is it supposed to work like that

**Comment by Kazooki123** [comment]
Yeah, just a bug but we'll fixed it. Not a big deal to be honest since in the beginning of LunarDB it already prints a lot of commands for you to follow unless you have a severe memory problem but yeah.
